[package]
name = "basic-sketch"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou.workspace = true


[[bin]]
name = "circle-animation-sketch"
path = "src/circle-animation-sketch.rs"
